#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__version__ = '0.0.1'
__description__ = 'A panflute filter to embed image into html in base64 format'

import panflute as pf

def action(elem, doc):
    if isinstance(elem, pf.Image):
        out = pf.shell(['convert', elem.url, 'inline:-'])
        elem.url = out.decode('utf-8')

    return elem

pf.run_filter(action)
